services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.8
    container_name: stock-clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_DB: stock
      CLICKHOUSE_USER: stock_admin
      CLICKHOUSE_PASSWORD: stock_admin_123
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    restart: unless-stopped

volumes:
  clickhouse_data:
  clickhouse_logs: